### ISSUE TITLE
Intent to Archive & Redirect

### ISSUE THREAD

**Issue by wesleyboar** [DesignSafe-CI/DS_Use_Case_template#53]
# My Understanding

### 2023 & Before

This [DesignSafe-CI/DS_Use_Case_template](https://github.com/DesignSafe-CI/DS_Use_Case_template) repository was **both** instruction (via its README) to add a Use Case doc **and** a way for public to add a Use Case doc. And it was previewed at [ds-use-case-preview.netlify.app](https://ds-use-case-preview.netlify.app/) and public at [www.designsafe-ci.org/ds-use-case/](https://www.designsafe-ci.org/ds-use-case/)

### 2023 & After

DS docs for Use Cases is now in [(**private**) DesignSafe-CI/DS-User-Guide:/user-guide/docs/usecases](https://github.com/DesignSafe-CI/DS-User-Guide/tree/main/user-guide/docs/usecases) and served at [(public) www.designsafe-ci.org/user-guide/](https://www.designsafe-ci.org/user-guide/).

# My Proposal

Replace this [DesignSafe-CI/DS_Use_Case_template](https://github.com/DesignSafe-CI/DS_Use_Case_template) repo with [(**private**) DesignSafe-CI/DS-User-Guide:/user-guide/docs/usecases](https://github.com/DesignSafe-CI/DS-User-Guide/tree/main/user-guide/docs/usecases) made public.

## Tasks

- [x] **Redirect** [/ds-use-case/](http://designsafe-ci.org/ds-use-case/) URL to [/user-guide/usecases/](https://www.designsafe-ci.org/user-guide/usecases/).
- [x] **Move** and **adapt** instructions to [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide).
- [x] **Open** [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide) to the public.
- [x] 🆕 **Redirect** [DS_Use_Case_template](https://github.com/DesignSafe-CI/DS_Use_Case_template) visitors to [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide).
- [x] **Archive** [DS_Use_Case_template](https://github.com/DesignSafe-CI/DS_Use_Case_template).
  <sub>https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/56</sub>
- [ ] **Replicate** or **Retire** [ds-use-case-preview.netlify.app](https://ds-use-case-preview.netlify.app/).
  <sub>https://github.com/DesignSafe-CI/DS-User-Guide/issues/61</sub>

**Comment by kks32** [comment]
@wesleyboar This sounds good to me. I created the netlify app, so let me know when you like to disable or redirect it.

**Comment by wesleyboar** [comment]
@wesleyboar, you track this task via [DES-2668](https://tacc-main.atlassian.net/browse/DES-2668).

**Comment by wesleyboar** [comment]
@kks32 Will do, thanks.

**Comment by wesleyboar** [comment]
@kks32,

1. I migrate the README via ~~[DesignSafe-CI/DS-User-Guide#12](https://example.com)~~ [outdated inaccurate link]. I will request you have access, so you may review and contribute.
2. I read step 11, "After a minute or so a preview deployment of your use case will be available on the pull request page." That's great — a preview per branch auto-deployed! I would love your help to replicate this for https://github.com/DesignSafe-CI/DS-User-Guide/. **Are you available to collaborate?**

**Comment by wesleyboar** [comment]
Oh, also, I've found some direction on #8 by @rstijerina. I'll see how far that takes me.

**Comment by wesleyboar** [comment]
### Status

- …
- [x] **Move** and **adapt** instructions to [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide)
    <sub>https://github.com/DesignSafe-CI/DS-User-Guide/pull/12</sub>
    <sub>The [DS-User-Guide has "Contributing" section README](https://github.com/DesignSafe-CI/DS-User-Guide/blob/main/README.md#contributing).</sub>
- [x] **Open** [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide) to the public.
- …
- **Replicate** or **retire** [ds-use-case-preview.netlify.app](https://ds-use-case-preview.netlify.app/).
    - [x] Add build workflow for Netlify to use (https://github.com/DesignSafe-CI/DS-User-Guide/commit/b9a70a5).
    - [x] Ask @kks32 to update his Netlify app config to use DS-User-Guide build.
    - …

**Comment by wesleyboar** [comment]
A while back I redirected [/ds-use-case/](http://designsafe-ci.org/ds-use-case/) to [/user-guide/usecases/](https://www.designsafe-ci.org/user-guide/usecases/).

I plan to point visitors from this repo to [the new one](https://github.com/DesignSafe-CI/DS-User-Guide).

And the Netlify thing must be replicated…
- I started in [`.github/workflows/build-preview.yml`](https://github.com/DesignSafe-CI/DS-User-Guide/blob/main/.github/workflows/build-preview.yml).
- I added ["Local Testing" steps in REAMDE](https://github.com/DesignSafe-CI/DS-User-Guide?tab=readme-ov-file#local-testing), but contributors are **not** testing.

**Comment by wesleyboar** [comment]
### Status

1. https://github.com/DesignSafe-CI/DS_Use_Case_template/pull/56
2. https://github.com/DesignSafe-CI/DS-User-Guide/issues/61

**Comment by wesleyboar** [comment]
~~@kks32, you may retire/archive this repository, because [DS-User-Guide](https://github.com/DesignSafe-CI/DS-User-Guide/) has automatic preview deploys via Netlify, since [v3](https://github.com/DesignSafe-CI/DS-User-Guide/releases/tag/v3.0.0) (released today).~~

<sup>@wesleyboar, when repo is archived, update [CMD-204](https://tacc-main.atlassian.net/browse/CMD-204).</sup>

**Comment by wesleyboar** [comment]
Request moved to [internal ticket](https://tacc-main.atlassian.net/browse/DSAPP-125).
